name: Run Trend Checker

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  run-trend-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Call Render cron endpoint
        run: curl -X GET https://nft-trend-line-bot.onrender.com/cron
